# Generated by Django 4.0.4 on 2022-04-22 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='id_state', on_delete=django.db.models.deletion.DO_NOTHING, related_name='states', to='core.state'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(db_column='id_city', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='core.city'),
        ),
        migrations.AlterField(
            model_name='district',
            name='zone',
            field=models.ForeignKey(db_column='id_zone', on_delete=django.db.models.deletion.DO_NOTHING, related_name='zones', to='core.zone'),
        ),
    ]
