# Generated by Django 4.0.4 on 2022-04-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_city_state_alter_district_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(default=True, max_length=64, unique=True),
        ),
    ]
